/**
 * This class is generated by jOOQ
 */
package com.staypal.db.tables;


import com.staypal.db.Keys;
import com.staypal.db.Staypaldb;
import com.staypal.db.tables.records.UsersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends TableImpl<UsersRecord> {

    private static final long serialVersionUID = 403151869;

    /**
     * The reference instance of <code>staypaldb.users</code>
     */
    public static final Users USERS = new Users();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersRecord> getRecordType() {
        return UsersRecord.class;
    }

    /**
     * The column <code>staypaldb.users.password</code>.
     */
    public final TableField<UsersRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(1023), this, "");

    /**
     * The column <code>staypaldb.users.salt</code>.
     */
    public final TableField<UsersRecord, String> SALT = createField("salt", org.jooq.impl.SQLDataType.VARCHAR.length(127), this, "");

    /**
     * The column <code>staypaldb.users.email</code>.
     */
    public final TableField<UsersRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>staypaldb.users.phone</code>.
     */
    public final TableField<UsersRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>staypaldb.users.neighborhood</code>.
     */
    public final TableField<UsersRecord, String> NEIGHBORHOOD = createField("neighborhood", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>staypaldb.users.how_hear</code>.
     */
    public final TableField<UsersRecord, String> HOW_HEAR = createField("how_hear", org.jooq.impl.SQLDataType.VARCHAR.length(1023), this, "");

    /**
     * The column <code>staypaldb.users.other_comments</code>.
     */
    public final TableField<UsersRecord, String> OTHER_COMMENTS = createField("other_comments", org.jooq.impl.SQLDataType.VARCHAR.length(1023), this, "");

    /**
     * The column <code>staypaldb.users.need_rides</code>.
     */
    public final TableField<UsersRecord, Byte> NEED_RIDES = createField("need_rides", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.need_food</code>.
     */
    public final TableField<UsersRecord, Byte> NEED_FOOD = createField("need_food", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.need_childcare</code>.
     */
    public final TableField<UsersRecord, Byte> NEED_CHILDCARE = createField("need_childcare", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.need_housing</code>.
     */
    public final TableField<UsersRecord, Byte> NEED_HOUSING = createField("need_housing", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.need_translation</code>.
     */
    public final TableField<UsersRecord, Byte> NEED_TRANSLATION = createField("need_translation", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.need_court</code>.
     */
    public final TableField<UsersRecord, Byte> NEED_COURT = createField("need_court", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.name</code>.
     */
    public final TableField<UsersRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>staypaldb.users.nw</code>.
     */
    public final TableField<UsersRecord, Byte> NW = createField("nw", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.ne</code>.
     */
    public final TableField<UsersRecord, Byte> NE = createField("ne", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.sw</code>.
     */
    public final TableField<UsersRecord, Byte> SW = createField("sw", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.se</code>.
     */
    public final TableField<UsersRecord, Byte> SE = createField("se", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.va</code>.
     */
    public final TableField<UsersRecord, Byte> VA = createField("va", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>staypaldb.users.md</code>.
     */
    public final TableField<UsersRecord, Byte> MD = createField("md", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>staypaldb.users</code> table reference
     */
    public Users() {
        this("users", null);
    }

    /**
     * Create an aliased <code>staypaldb.users</code> table reference
     */
    public Users(String alias) {
        this(alias, USERS);
    }

    private Users(String alias, Table<UsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Users(String alias, Table<UsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Staypaldb.STAYPALDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UsersRecord> getPrimaryKey() {
        return Keys.KEY_USERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UsersRecord>> getKeys() {
        return Arrays.<UniqueKey<UsersRecord>>asList(Keys.KEY_USERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users as(String alias) {
        return new Users(alias, this);
    }

    /**
     * Rename this table
     */
    public Users rename(String name) {
        return new Users(name, null);
    }
}
