/**
 * This class is generated by jOOQ
 */
package com.staypal.db.tables;


import com.staypal.db.Staypaldb;
import com.staypal.db.tables.records.UsersRecord;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends TableImpl<UsersRecord> {

    private static final long serialVersionUID = 1350593575;

    /**
     * The reference instance of <code>staypaldb.users</code>
     */
    public static final Users USERS = new Users();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersRecord> getRecordType() {
        return UsersRecord.class;
    }

    /**
     * The column <code>staypaldb.users.username</code>.
     */
    public final TableField<UsersRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>staypaldb.users.password</code>.
     */
    public final TableField<UsersRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(1023), this, "");

    /**
     * The column <code>staypaldb.users.salt</code>.
     */
    public final TableField<UsersRecord, String> SALT = createField("salt", org.jooq.impl.SQLDataType.VARCHAR.length(127), this, "");

    /**
     * The column <code>staypaldb.users.birthday</code>.
     */
    public final TableField<UsersRecord, Date> BIRTHDAY = createField("birthday", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>staypaldb.users.email</code>.
     */
    public final TableField<UsersRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>staypaldb.users.hometown</code>.
     */
    public final TableField<UsersRecord, String> HOMETOWN = createField("hometown", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>staypaldb.users.host_city</code>.
     */
    public final TableField<UsersRecord, String> HOST_CITY = createField("host_city", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>staypaldb.users.low_rate</code>.
     */
    public final TableField<UsersRecord, Double> LOW_RATE = createField("low_rate", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>staypaldb.users.max_pay</code>.
     */
    public final TableField<UsersRecord, Double> MAX_PAY = createField("max_pay", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>staypaldb.users.season</code>.
     */
    public final TableField<UsersRecord, String> SEASON = createField("season", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>staypaldb.users.experience_type</code>.
     */
    public final TableField<UsersRecord, String> EXPERIENCE_TYPE = createField("experience_type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>staypaldb.users.description</code>.
     */
    public final TableField<UsersRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1023), this, "");

    /**
     * Create a <code>staypaldb.users</code> table reference
     */
    public Users() {
        this("users", null);
    }

    /**
     * Create an aliased <code>staypaldb.users</code> table reference
     */
    public Users(String alias) {
        this(alias, USERS);
    }

    private Users(String alias, Table<UsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Users(String alias, Table<UsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Staypaldb.STAYPALDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users as(String alias) {
        return new Users(alias, this);
    }

    /**
     * Rename this table
     */
    public Users rename(String name) {
        return new Users(name, null);
    }
}
