/**
 * This class is generated by jOOQ
 */
package com.staypal.db.tables.records;


import com.staypal.db.tables.Users;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record12<String, String, String, Date, String, String, String, Double, Double, String, String, String> {

    private static final long serialVersionUID = -1989633681;

    /**
     * Setter for <code>staypaldb.users.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>staypaldb.users.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>staypaldb.users.password</code>.
     */
    public void setPassword(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>staypaldb.users.password</code>.
     */
    public String getPassword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>staypaldb.users.salt</code>.
     */
    public void setSalt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>staypaldb.users.salt</code>.
     */
    public String getSalt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>staypaldb.users.birthday</code>.
     */
    public void setBirthday(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>staypaldb.users.birthday</code>.
     */
    public Date getBirthday() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>staypaldb.users.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>staypaldb.users.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>staypaldb.users.hometown</code>.
     */
    public void setHometown(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>staypaldb.users.hometown</code>.
     */
    public String getHometown() {
        return (String) get(5);
    }

    /**
     * Setter for <code>staypaldb.users.host_city</code>.
     */
    public void setHostCity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>staypaldb.users.host_city</code>.
     */
    public String getHostCity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>staypaldb.users.low_rate</code>.
     */
    public void setLowRate(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>staypaldb.users.low_rate</code>.
     */
    public Double getLowRate() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>staypaldb.users.max_pay</code>.
     */
    public void setMaxPay(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>staypaldb.users.max_pay</code>.
     */
    public Double getMaxPay() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>staypaldb.users.season</code>.
     */
    public void setSeason(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>staypaldb.users.season</code>.
     */
    public String getSeason() {
        return (String) get(9);
    }

    /**
     * Setter for <code>staypaldb.users.experience_type</code>.
     */
    public void setExperienceType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>staypaldb.users.experience_type</code>.
     */
    public String getExperienceType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>staypaldb.users.description</code>.
     */
    public void setDescription(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>staypaldb.users.description</code>.
     */
    public String getDescription() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, Date, String, String, String, Double, Double, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, Date, String, String, String, Double, Double, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Users.USERS.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Users.USERS.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Users.USERS.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Users.USERS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Users.USERS.HOMETOWN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Users.USERS.HOST_CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return Users.USERS.LOW_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return Users.USERS.MAX_PAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Users.USERS.SEASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Users.USERS.EXPERIENCE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Users.USERS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getHometown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getHostCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getLowRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getMaxPay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSeason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getExperienceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(Date value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value6(String value) {
        setHometown(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value7(String value) {
        setHostCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value8(Double value) {
        setLowRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value9(Double value) {
        setMaxPay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value10(String value) {
        setSeason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value11(String value) {
        setExperienceType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value12(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(String value1, String value2, String value3, Date value4, String value5, String value6, String value7, Double value8, Double value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String username, String password, String salt, Date birthday, String email, String hometown, String hostCity, Double lowRate, Double maxPay, String season, String experienceType, String description) {
        super(Users.USERS);

        set(0, username);
        set(1, password);
        set(2, salt);
        set(3, birthday);
        set(4, email);
        set(5, hometown);
        set(6, hostCity);
        set(7, lowRate);
        set(8, maxPay);
        set(9, season);
        set(10, experienceType);
        set(11, description);
    }
}
