/**
 * This class is generated by jOOQ
 */
package com.staypal.db.tables.records;


import com.staypal.db.tables.Users;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record20<String, String, String, String, String, String, String, Byte, Byte, Byte, Byte, Byte, Byte, String, Byte, Byte, Byte, Byte, Byte, Byte> {

    private static final long serialVersionUID = 687733708;

    /**
     * Setter for <code>staypaldb.users.password</code>.
     */
    public void setPassword(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>staypaldb.users.password</code>.
     */
    public String getPassword() {
        return (String) get(0);
    }

    /**
     * Setter for <code>staypaldb.users.salt</code>.
     */
    public void setSalt(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>staypaldb.users.salt</code>.
     */
    public String getSalt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>staypaldb.users.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>staypaldb.users.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>staypaldb.users.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>staypaldb.users.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>staypaldb.users.neighborhood</code>.
     */
    public void setNeighborhood(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>staypaldb.users.neighborhood</code>.
     */
    public String getNeighborhood() {
        return (String) get(4);
    }

    /**
     * Setter for <code>staypaldb.users.how_hear</code>.
     */
    public void setHowHear(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>staypaldb.users.how_hear</code>.
     */
    public String getHowHear() {
        return (String) get(5);
    }

    /**
     * Setter for <code>staypaldb.users.other_comments</code>.
     */
    public void setOtherComments(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>staypaldb.users.other_comments</code>.
     */
    public String getOtherComments() {
        return (String) get(6);
    }

    /**
     * Setter for <code>staypaldb.users.need_rides</code>.
     */
    public void setNeedRides(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>staypaldb.users.need_rides</code>.
     */
    public Byte getNeedRides() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>staypaldb.users.need_food</code>.
     */
    public void setNeedFood(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>staypaldb.users.need_food</code>.
     */
    public Byte getNeedFood() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>staypaldb.users.need_childcare</code>.
     */
    public void setNeedChildcare(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>staypaldb.users.need_childcare</code>.
     */
    public Byte getNeedChildcare() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>staypaldb.users.need_housing</code>.
     */
    public void setNeedHousing(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>staypaldb.users.need_housing</code>.
     */
    public Byte getNeedHousing() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>staypaldb.users.need_translation</code>.
     */
    public void setNeedTranslation(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>staypaldb.users.need_translation</code>.
     */
    public Byte getNeedTranslation() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>staypaldb.users.need_court</code>.
     */
    public void setNeedCourt(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>staypaldb.users.need_court</code>.
     */
    public Byte getNeedCourt() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>staypaldb.users.name</code>.
     */
    public void setName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>staypaldb.users.name</code>.
     */
    public String getName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>staypaldb.users.nw</code>.
     */
    public void setNw(Byte value) {
        set(14, value);
    }

    /**
     * Getter for <code>staypaldb.users.nw</code>.
     */
    public Byte getNw() {
        return (Byte) get(14);
    }

    /**
     * Setter for <code>staypaldb.users.ne</code>.
     */
    public void setNe(Byte value) {
        set(15, value);
    }

    /**
     * Getter for <code>staypaldb.users.ne</code>.
     */
    public Byte getNe() {
        return (Byte) get(15);
    }

    /**
     * Setter for <code>staypaldb.users.sw</code>.
     */
    public void setSw(Byte value) {
        set(16, value);
    }

    /**
     * Getter for <code>staypaldb.users.sw</code>.
     */
    public Byte getSw() {
        return (Byte) get(16);
    }

    /**
     * Setter for <code>staypaldb.users.se</code>.
     */
    public void setSe(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>staypaldb.users.se</code>.
     */
    public Byte getSe() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>staypaldb.users.va</code>.
     */
    public void setVa(Byte value) {
        set(18, value);
    }

    /**
     * Getter for <code>staypaldb.users.va</code>.
     */
    public Byte getVa() {
        return (Byte) get(18);
    }

    /**
     * Setter for <code>staypaldb.users.md</code>.
     */
    public void setMd(Byte value) {
        set(19, value);
    }

    /**
     * Getter for <code>staypaldb.users.md</code>.
     */
    public Byte getMd() {
        return (Byte) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<String, String, String, String, String, String, String, Byte, Byte, Byte, Byte, Byte, Byte, String, Byte, Byte, Byte, Byte, Byte, Byte> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<String, String, String, String, String, String, String, Byte, Byte, Byte, Byte, Byte, Byte, String, Byte, Byte, Byte, Byte, Byte, Byte> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Users.USERS.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Users.USERS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Users.USERS.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Users.USERS.NEIGHBORHOOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Users.USERS.HOW_HEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Users.USERS.OTHER_COMMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Users.USERS.NEED_RIDES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Users.USERS.NEED_FOOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return Users.USERS.NEED_CHILDCARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return Users.USERS.NEED_HOUSING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return Users.USERS.NEED_TRANSLATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field13() {
        return Users.USERS.NEED_COURT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Users.USERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field15() {
        return Users.USERS.NW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field16() {
        return Users.USERS.NE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field17() {
        return Users.USERS.SW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field18() {
        return Users.USERS.SE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field19() {
        return Users.USERS.VA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field20() {
        return Users.USERS.MD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNeighborhood();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getHowHear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getOtherComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getNeedRides();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getNeedFood();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getNeedChildcare();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getNeedHousing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getNeedTranslation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value13() {
        return getNeedCourt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value15() {
        return getNw();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value16() {
        return getNe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value17() {
        return getSw();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value18() {
        return getSe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value19() {
        return getVa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value20() {
        return getMd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(String value) {
        setNeighborhood(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value6(String value) {
        setHowHear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value7(String value) {
        setOtherComments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value8(Byte value) {
        setNeedRides(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value9(Byte value) {
        setNeedFood(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value10(Byte value) {
        setNeedChildcare(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value11(Byte value) {
        setNeedHousing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value12(Byte value) {
        setNeedTranslation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value13(Byte value) {
        setNeedCourt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value14(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value15(Byte value) {
        setNw(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value16(Byte value) {
        setNe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value17(Byte value) {
        setSw(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value18(Byte value) {
        setSe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value19(Byte value) {
        setVa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value20(Byte value) {
        setMd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Byte value8, Byte value9, Byte value10, Byte value11, Byte value12, Byte value13, String value14, Byte value15, Byte value16, Byte value17, Byte value18, Byte value19, Byte value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String password, String salt, String email, String phone, String neighborhood, String howHear, String otherComments, Byte needRides, Byte needFood, Byte needChildcare, Byte needHousing, Byte needTranslation, Byte needCourt, String name, Byte nw, Byte ne, Byte sw, Byte se, Byte va, Byte md) {
        super(Users.USERS);

        set(0, password);
        set(1, salt);
        set(2, email);
        set(3, phone);
        set(4, neighborhood);
        set(5, howHear);
        set(6, otherComments);
        set(7, needRides);
        set(8, needFood);
        set(9, needChildcare);
        set(10, needHousing);
        set(11, needTranslation);
        set(12, needCourt);
        set(13, name);
        set(14, nw);
        set(15, ne);
        set(16, sw);
        set(17, se);
        set(18, va);
        set(19, md);
    }
}
