/**
 * This class is generated by jOOQ
 */
package com.staypal.db;


import com.staypal.db.tables.AuthTokens;
import com.staypal.db.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staypaldb extends SchemaImpl {

    private static final long serialVersionUID = 1614216165;

    /**
     * The reference instance of <code>staypaldb</code>
     */
    public static final Staypaldb STAYPALDB = new Staypaldb();

    /**
     * The table <code>staypaldb.auth_tokens</code>.
     */
    public final AuthTokens AUTH_TOKENS = com.staypal.db.tables.AuthTokens.AUTH_TOKENS;

    /**
     * The table <code>staypaldb.users</code>.
     */
    public final Users USERS = com.staypal.db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Staypaldb() {
        super("staypaldb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AuthTokens.AUTH_TOKENS,
            Users.USERS);
    }
}
