/**
 * This class is generated by jOOQ
 */
package com.staypal.db;


import com.staypal.db.tables.AuthTokens;
import com.staypal.db.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in staypaldb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>staypaldb.auth_tokens</code>.
     */
    public static final AuthTokens AUTH_TOKENS = com.staypal.db.tables.AuthTokens.AUTH_TOKENS;

    /**
     * The table <code>staypaldb.users</code>.
     */
    public static final Users USERS = com.staypal.db.tables.Users.USERS;
}
